package mapreduce

import (
	"hash/fnv"
	"io/ioutil"
	"log"
	"encoding/json"
	"os"
	"fmt"
)

// doMap manages one map task: it reads one of the input files
// (inFile), calls the user-defined map function (mapF) for that file's
// contents, and partitions the output into nReduce intermediate files.
func doMap(
	jobName string, // the name of the MapReduce job
	mapTaskNumber int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(file string, contents string) []KeyValue,
) {
	//
	// You will need to write this function.
	//
	// The intermediate output of a map task is stored as multiple
	// files, one per destination reduce task. The file name includes
	// both the map task number and the reduce task number. Use the
	// filename generated by reduceName(jobName, mapTaskNumber, r) as
	// the intermediate file for reduce task r. Call ihash() (see below)
	// on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//
	// Look at Go's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	//
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be JSON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//
	c, err := ioutil.ReadFile(inFile)
	checkErr(err, fmt.Sprintf("Failed to read file: %s for map task", inFile))

	mapResults := mapF(inFile, string(c))

	// Create intermediate files
	encoders := make([]*json.Encoder, nReduce)

	for i := 0; i < nReduce; i++ {
		fname := reduceName(jobName, mapTaskNumber, i)
		f, err := os.Create(fname)
		defer f.Close()
		checkErr(err, fmt.Sprintf("Failed to create intermediate output file: %s", fname))

		encoders[i] = json.NewEncoder(f)
	}

	// Write map results to intermediate file in json format
	for _, kv := range mapResults {
		idx := ihash(kv.Key) % nReduce
		err := encoders[idx].Encode(&kv)
		checkErr(err, fmt.Sprintf("Failed to encode: %s to file", kv))
	}
}

func checkErr(err error, logging string) {
	if err != nil {
		log.Fatalf("%s, %s", logging, err)
	}
}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
